framework/default/ortoo-core/default/objects/Logging_Configuration__c/Logging_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configures, for example the logging levels that should generate log entries</description>
    <label>Logging Configuration</label>
</CustomObject>

framework/default/ortoo-core/default/objects/Logging_Configuration__c/fields/Log_ERROR_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_ERROR_Level_Messages__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should messages with the level of &apos;ERROR&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;ERROR&apos; be logged?</inlineHelpText>
    <label>Log ERROR Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/objects/Logging_Configuration__c/fields/Log_INFO_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_INFO_Level_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should messages with the level of &apos;INFO&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;INFO&apos; be logged?</inlineHelpText>
    <label>Log INFO Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/modules/logger/services/logger/objects/Logging_Configuration__c/fields/Log_WARNING_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_WARNING_Level_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should messages with the level of &apos;WARNING&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;WARNING&apos; be logged?</inlineHelpText>
    <label>Log WARNING Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/modules/logger/services/logger/classes/LoggerService.cls
public inherited sharing class LoggerService
{
	public enum Level { INFO, WARNING, ERROR }

	public static final Level EXCEPTION_LOG_LEVEL = Level.ERROR;

    public static void log( LoggerService.Level logLevel, String message )
	{
		if ( ! shouldLog( logLevel ) )
		{
			return;
		}

		service().log( logLevel, message );
	}

    public static void log( LoggerService.Level logLevel, String message, Id relatedSobjectId )
	{
		if ( ! shouldLog( logLevel ) )
		{
			return;
		}

		service().log( logLevel, message, relatedSobjectId );
	}

	public static void log( Exception exceptionToLog )
	{
		if ( ! shouldLogExceptions() )
		{
			return;
		}

		if ( exceptionToLog instanceOf DmlException )
		{
			service().log( (DmlException)exceptionToLog );
		}
		if ( exceptionToLog instanceOf ortoo_Exception )
		{
			service().log( (ortoo_Exception)exceptionToLog );
		}
		service().log( exceptionToLog );
	}

	public static void log( DmlException exceptionToLog )
	{
		if ( ! shouldLogExceptions() )
		{
			return;
		}

		service().log( exceptionToLog );
	}

	public static void log( ortoo_Exception exceptionToLog )
	{
		if ( ! shouldLogExceptions() )
		{
			return;
		}

		service().log( exceptionToLog );
	}

	public static void log( Exception exceptionToLog, Id relatedSobjectId )
	{
		if ( ! shouldLogExceptions() )
		{
			return;
		}

		service().log( exceptionToLog, relatedSobjectId );
	}

	private static Boolean shouldLog( LoggerService.Level logLevel )
	{
		Logging_Configuration__c config = Logging_Configuration__c.getInstance();

		switch on logLevel {
			when INFO {
				return config.Id != null ? config.Log_INFO_Level_Messages__c : false; // if no config record exists, do not log INFO
			}
			when WARNING {
				return config.Id != null ? config.Log_WARNING_Level_Messages__c : false; // if no config record exists, do not log WARNING
			}
		}
		return config.Id != null ? config.Log_ERROR_Level_Messages__c : true; // if no config record exists, still log ERROR
	}

	private static Boolean shouldLogExceptions()
	{
		return shouldLog( EXCEPTION_LOG_LEVEL );
	}

    private static ILoggerService service()
	{
        return (ILoggerService)Application.SERVICE.newInstance( ILoggerService.class );
    }
}