framework/default/ortoo-core/default/objects/Logging_Configuration__c/Logging_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configures, for example the logging levels that should generate log entries</description>
    <label>Logging Configuration</label>
</CustomObject>

framework/default/ortoo-core/default/objects/Logging_Configuration__c/fields/Log_ERROR_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_ERROR_Level_Messages__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should messages with the level of &apos;ERROR&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;ERROR&apos; be logged?</inlineHelpText>
    <label>Log ERROR Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/objects/Logging_Configuration__c/fields/Log_INFO_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_INFO_Level_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should messages with the level of &apos;INFO&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;INFO&apos; be logged?</inlineHelpText>
    <label>Log INFO Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/modules/logger/services/logger/objects/Logging_Configuration__c/fields/Log_WARN_Level_Messages__c.field-meta.xml
<CustomField>
    <fullName>Log_WARN_Level_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should messages with the level of &apos;WARN&apos; be logged?</description>
    <inlineHelpText>Should messages with the level of &apos;WARN&apos; be logged?</inlineHelpText>
    <label>Log WARN Level Messages</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/classes/services/logger/tests/TestLoggerUtils.cls
@isTest
public with sharing class TestLoggerUtils
{
	public static void setLoggingLevels( List<LoggerService.Level> levelsToLog )
	{
		LoggerService.config = new Logging_Configuration__c(
			Name = 'Test configuration',
			Log_INFO_Level_Messages__c = levelsToLog.contains( LoggerService.Level.INFO ),
			Log_WARN_Level_Messages__c = levelsToLog.contains( LoggerService.Level.WARN ),
			Log_ERROR_Level_Messages__c = levelsToLog.contains( LoggerService.Level.ERROR )
		);
	}

	public static void switchLoggingToErrorOnly()
	{
		setLoggingLevels( new List<LoggerService.Level>{ LoggerService.Level.ERROR } );
	}

	public static void switchLoggingOff()
	{
		setLoggingLevels( new List<LoggerService.Level>() );
	}

	public static void switchLoggingOn()
	{
		setLoggingLevels( new List<LoggerService.Level>{ LoggerService.Level.INFO, LoggerService.Level.WARN, LoggerService.Level.ERROR } );
	}

	public static void setConfigurationMissing()
	{
		LoggerService.config = new Logging_Configuration__c();
	}

	/**
	 * Registers the test logger service and returns it.
	 *
	 * Also switches on logging at all levels.  If you require a different logging level, you can set it
	 * *after* registering the test logger
	 */
	public static TestLoggerService registerTestLoggerService()
	{
		switchLoggingOn();
		TestLoggerService testLogger = new TestLoggerService();
		Application.SERVICE.setMock( ILoggerService.class, testLogger );
		return testLogger;
	}
}