framework/default/ortoo-core/default/objects/Process_Deactivation__c/Process_Deactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides the ability to selectively deactivate processes / triggers and validation rules within the application.</description>
    <label>Process Deactivation</label>
</CustomObject>

framework/fflib/framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Flows__c.field-meta.xml
<CustomField>
    <fullName>Disable_Flows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all flows.  Assumes that flows look at this property before performing any actions.</description>
    <inlineHelpText>Disable all flows.  Assumes that flows look at this property before performing any actions.</inlineHelpText>
    <label>Disable Flows</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Processes__c.field-meta.xml
<CustomField>
    <fullName>Disable_Processes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Processes built in Process Builder.  Assumes that processes look at this property before performing any actions.</description>
    <inlineHelpText>Disable all Processes built in Process Builder.  Assumes that processes look at this property before performing any actions.</inlineHelpText>
    <label>Disable Processes</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable triggers.</description>
    <inlineHelpText>Disable triggers.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

framework/fflib/framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Triggers_By_Domain__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers_By_Domain__c</fullName>
    <description>Disable the triggers for the specifically listed domain classes - split by semicolon (e.g. Actions;AssignmentGroups).</description>
    <inlineHelpText>Disable the triggers for the specifically listed domain classes - split by semicolon (e.g. Actions;AssignmentGroups).</inlineHelpText>
    <label>Disable Triggers by Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>Disable_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Validation Rules.  Assumes that validation rules look at this property to determine if they should be enabled.</description>
    <inlineHelpText>Disable all Validation Rules.  Assumes that validation rules look at this property to determine if they should be enabled.</inlineHelpText>
    <label>Disable Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

framework/fflib/framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Workflows__c.field-meta.xml
<CustomField>
    <fullName>Disable_Workflows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Workflows.  Assumes that workflows look at this property to determine if they should be enabled.</description>
    <inlineHelpText>Disable all Workflows.  Assumes that workflows look at this property to determine if they should be enabled.</inlineHelpText>
    <label>Disable Workflows</label>
    <type>Checkbox</type>
</CustomField>

framework/default/ortoo-core/default/classes/test-utils/TestProcessDeactivationUtils.cls
/**
 * Utility class that provides the ability to disable process types in tests
 *
 * @group TestUtils
 */
@isTest
public with sharing class TestProcessDeactivationUtils
{
	/**
	 * Deactivate all processes in this app.
	 */
	public static void deactivateAll()
	{
		store( getDeactivateAll() );
	}

	/**
	 * Deactivate the trigger in the app that are served by the passed domain classes
	 */
	public static void deactivateTriggerByDomain( Type domain )
	{
		store( getDeactivateTriggersByDomain( new List<Type>{ domain } ) );
	}

	/**
	 * Deactivate the triggers in the app that are served by the passed domain classes
	 */
	public static void deactivateTriggersByDomain( List<Type> domains )
	{
		store( getDeactivateTriggersByDomain( domains ) );
	}

	/**
	 * Builds a Process Deactivation record for the current organisation, that states all processes should be deactivated.
	 *
	 * @return	Process_Deactivation__c	A Process Deactivation record that states all processes should be deactivated
	 */
	public static Process_Deactivation__c getDeactivateAll()
	{
		return build( true );
	}

	/**
	 * Builds a Process Deactivation record for the current organisation, that states all processes should be activated, other than the stated triggers.
	 *
	 * @return	Process_Deactivation__c	A Process Deactivation record that states the given domain triggers should be deactivated
	 */
	public static Process_Deactivation__c getDeactivateTriggersByDomain( List<Type> domains )
	{
		Contract.requires( domains != null, 'getDeactivateTriggersByDomain called with a null domains' );

		Process_Deactivation__c returnRecord = build( false );
		returnRecord.Disable_Triggers_By_Domain__c	= StringUtils.convertListToDelimitedString( domains );

		return returnRecord;
	}

	/**
	 * Stores the give process deactivation record, ensuing that any cached versions of them are cleared.
	 *
	 * @param	Process_Deactivation__c	The setting record to store
	 */
	public static void store( Process_Deactivation__c processDeactivationSetting )
	{
		insert processDeactivationSetting;
		ProcessDeactivation.clearSetting();
	}

	private static Process_Deactivation__c build( Boolean defaultValue )
	{
		return new Process_Deactivation__c
			(
				SetupOwnerId					= UserInfo.getOrganizationId(),
				Disable_Validation_Rules__c		= defaultValue,
				Disable_Triggers__c     		= defaultValue,
				Disable_Flows__c           		= defaultValue,
				Disable_Processes__c       		= defaultValue,
				Disable_Workflows__c       		= defaultValue
			);
	}
}