framework/default/ortoo-core/default/objects/Process_Deactivation__c/Process_Deactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides the ability to selectively deactivate processes / triggers and validation rules within the application.</description>
    <label>Process Deactivation</label>
</CustomObject>

framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable triggers.</description>
    <inlineHelpText>Disable triggers.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

framework/fflib/framework/default/ortoo-core/default/objects/Process_Deactivation__c/fields/Disable_Triggers_By_Domain__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers_By_Domain__c</fullName>
    <description>Disable the triggers for the specifically listed domain classes - split by semicolon (e.g. Actions;AssignmentGroups).</description>
    <inlineHelpText>Disable the triggers for the specifically listed domain classes - split by semicolon (e.g. Actions;AssignmentGroups).</inlineHelpText>
    <label>Disable Triggers by Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

framework/fflib/framework/default/ortoo-core/default/classes/ProcessDeactivation.cls
/**
 * Provides the ability to check if given things are deactivated via configuration
 */
public class ProcessDeactivation
{
    @testVisible
    private static Process_Deactivation__c processDeactivationSetting
    {
        get
        {
            if ( processDeactivationSetting == null )
            {
                processDeactivationSetting = Process_Deactivation__c.getInstance();
            }
            return processDeactivationSetting;
        }
        set;
    }

    /**
     * Clears the currently cached setting so it is reloaded on the next reference
     */
    public static void clearSetting()
    {
        processDeactivationSetting = null;
    }

    /**
     * States if the given trigger's domain type is deactivated.
     *
     * @param   Type    The domain type to check (e.g. Actions.class)
     * @return  Boolean States if the domain type is active, when considered for triggers
     */
    public static Boolean triggersDeactivated( Type domainType )
    {
        Contract.requires( domainType != null, 'triggersDeactivated called with a null domainType' );

        if ( processDeactivationSetting.Disable_Triggers__c )
        {
            return true;
        }

        List<String> deactivatedDomains = StringUtils.convertDelimitedStringToList( processDeactivationSetting.Disable_Triggers_By_Domain__c );
        return ( deactivatedDomains.contains( domainType.toString() ) );
    }
}